# CI config by T. Yoshida with a little YAML help from ChatGPT
name: Run Bonus Drink

on:
  workflow_dispatch:
  push:
    branches:
#      - main
      - my_answer

jobs:
  run-bonus-drink:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Rubyバージョンは必要に応じて調整

      - name: Run script
        run: ruby bonus_drink.rb
